-- ================================================================
-- Inventory category cleanup
-- 1. Merges short codes into full names
-- 2. Re-categorizes MISC/SHOP SUPPLIES items by keyword
-- ================================================================

BEGIN;

-- STEP 1: Normalize short category codes to full names

UPDATE inventory SET category = 'ELECTRICAL', updated_at = NOW()
WHERE category = 'ELEC';

UPDATE inventory SET category = 'PLUMBING', updated_at = NOW()
WHERE category = 'PLMB';

UPDATE inventory SET category = 'HARDWARE', updated_at = NOW()
WHERE category = 'HDWR';

UPDATE inventory SET category = 'ROOFING', updated_at = NOW()
WHERE category = 'ROOF';

UPDATE inventory SET category = 'DOORS/WINDOWS/AWNINGS', updated_at = NOW()
WHERE category = 'DOOR';

UPDATE inventory SET category = 'SOLAR', updated_at = NOW()
WHERE category = 'SOLR';

UPDATE inventory SET category = 'TOWING/CHASSIS', updated_at = NOW()
WHERE category = 'TOW';

UPDATE inventory SET category = 'HVAC', updated_at = NOW()
WHERE category = 'HVAC';

UPDATE inventory SET category = 'MISC/SHOP SUPPLIES', updated_at = NOW()
WHERE category = 'MISC';

-- STEP 2: Re-categorize items incorrectly stuck in MISC/SHOP SUPPLIES

-- → SOLAR
UPDATE inventory SET category = 'SOLAR', updated_at = NOW()
WHERE category = 'MISC/SHOP SUPPLIES'
  AND (
       UPPER(description) LIKE '%SOLAR%'
       OR UPPER(description) LIKE '%RENOGY%'
       OR UPPER(description) LIKE '%VICTRON%'
       OR UPPER(description) LIKE '%LITHIUM%'
       OR UPPER(description) LIKE '%LIFEPO4%'
       OR UPPER(description) LIKE '%BATTLEBORN%'
       OR UPPER(description) LIKE '%EPOCH 300%'
       OR UPPER(description) LIKE '%SMARTSHUNT%'
       OR UPPER(description) LIKE '%MULTIPLUS%'
       OR UPPER(description) LIKE '%DC TO DC CHARG%'
       OR UPPER(description) LIKE '%MPPT%'
       OR UPPER(description) LIKE '%CHARGE CONTROL%'
       OR UPPER(description) LIKE '%SHADOWFLUX%'
       OR UPPER(description) LIKE '%ZAMP%'
       OR UPPER(description) LIKE '%GOPOWER%'
       OR UPPER(description) LIKE '%PULSE WAVE%'
       OR UPPER(description) LIKE '%HEAT BATTERY%'
       OR UPPER(description) LIKE '%AGM BATTERY%'
       OR UPPER(description) LIKE '%DEEP CYCLE%'
       OR UPPER(description) LIKE '%GROUP 24%'
       OR UPPER(description) LIKE '%GROUP 27%'
       OR UPPER(description) LIKE '%BUSBAR%'
       OR UPPER(description) LIKE '%BUS BAR%'
       OR UPPER(description) LIKE '%300AMP%'
       OR UPPER(description) LIKE '%BATTERY LUG%'
       OR UPPER(description) LIKE '%BATTER LUG%'
       OR UPPER(description) LIKE '%COPPER LUG%'
       OR UPPER(description) LIKE '%WELDING CABLE%'
       OR UPPER(description) LIKE '%WELDING CAB%'
       OR UPPER(description) LIKE '%AWG%'
       OR UPPER(description) LIKE '%1/0 GAUGE%'
       OR UPPER(description) LIKE '%2/0 GAUGE%'
       OR UPPER(description) LIKE '%4/0 GAUGE%'
       OR UPPER(description) LIKE '%FLEXAPRENE%'
       OR UPPER(description) LIKE '%BATTERY JUMP%'
       OR UPPER(description) LIKE '%JUMP STARTER%'
  );

-- → HVAC
UPDATE inventory SET category = 'HVAC', updated_at = NOW()
WHERE category = 'MISC/SHOP SUPPLIES'
  AND (
       UPPER(description) LIKE '%FURNACE%'
       OR UPPER(description) LIKE '%ATWOOD%'
       OR UPPER(description) LIKE '%DOMETIC HEAT%'
       OR UPPER(description) LIKE '%DOMETIC FRESH%'
       OR UPPER(description) LIKE '%COLEMAN MACH%'
       OR UPPER(description) LIKE '%COLEMAN-MACH%'
       OR UPPER(description) LIKE '%MAXXFAN%'
       OR UPPER(description) LIKE '%MAXX AIR%'
       OR UPPER(description) LIKE '%SAIL SWITCH%'
       OR UPPER(description) LIKE '%HEATING ELEMENT%'
       OR UPPER(description) LIKE '%THERMAL CUT%'
       OR UPPER(description) LIKE '%COOKTOP%'
       OR UPPER(description) LIKE '%STOVE BURN%'
       OR UPPER(description) LIKE '%REFRIGERANT%'
       OR UPPER(description) LIKE '%PENGUIN%'
       OR UPPER(description) LIKE '%PENQUIN%'
       OR UPPER(description) LIKE '%BRISK AIR%'
       OR UPPER(description) LIKE '%FRESH JET%'
       OR UPPER(description) LIKE '%MACH 8%'
       OR UPPER(description) LIKE '%MACH 15%'
       OR UPPER(description) LIKE '%AC MOUNTING%'
       OR UPPER(description) LIKE '%AC CEILING%'
       OR UPPER(description) LIKE '%AIR DISTRIBUTION%'
       OR UPPER(description) LIKE '%START RUN CAP%'
       OR UPPER(description) LIKE '%RANGE HOOD%'
       OR UPPER(description) LIKE '%BARALDI%'
       OR UPPER(description) LIKE '%FAN BLADE%'
       OR UPPER(description) LIKE '%VENT FAN MOTOR%'
       OR UPPER(description) LIKE '%FANTASTIC FAN%'
       OR UPPER(description) LIKE '%BATHROOM VENT FAN%'
       OR UPPER(description) LIKE '%EXHAUST FAN 14%'
       OR UPPER(description) LIKE '%WHITE DOME ASSEMBLY%'
       OR UPPER(description) LIKE '%VENT LID%'
       OR UPPER(description) LIKE '%SMOKE DOME%'
       OR UPPER(description) LIKE '%MAXXAIR VENT%'
       OR UPPER(description) LIKE '%MAXXAIR SMOKED%'
       OR UPPER(description) LIKE '%AIR RETURN VENT%'
       OR UPPER(description) LIKE '%HEATING/COOLING REGISTER%'
       OR UPPER(description) LIKE '%REGISTER FLOOR%'
       OR UPPER(description) LIKE '%DOMETIC AIR GRILLE%'
       OR UPPER(description) LIKE '%HEKI%'
       OR UPPER(description) LIKE '%SHROUD%'
       OR UPPER(description) LIKE '%FURRION AC%'
       OR UPPER(description) LIKE '%RECPRO AC%'
       OR UPPER(description) LIKE '%NORCOLD%'
       OR UPPER(description) LIKE '%LP GAS ALARM%'
       OR UPPER(description) LIKE '%PROPANE DETECT%'
       OR UPPER(description) LIKE '%CO ALARM%'
       OR UPPER(description) LIKE '%SAFE T ALERT%'
       OR UPPER(description) LIKE '%DUAL LP%'
       OR UPPER(description) LIKE '%CARBON MONOXIDE%'
       OR UPPER(description) LIKE '%HOLDING TANK TREATMENT%'
       OR UPPER(description) LIKE '%DIGEST-IT%'
       OR UPPER(description) LIKE '%TANK TREATMENT%'
       OR UPPER(description) LIKE '%HOLDING TANK PATCH%'
       OR UPPER(description) LIKE '%GEN AIR FILTER%'
       OR UPPER(description) LIKE '%TAIL PIPE%'
       OR UPPER(description) LIKE '%EXHAUST CO%'
       OR UPPER(description) LIKE '%MOTOR 12V FUR%'
       OR UPPER(description) LIKE '%ROUND VENT 6%'
       OR UPPER(description) LIKE '%EXTERIOR VENT%'
       OR UPPER(description) LIKE '%GIRARD WATER HEATER%'
       OR UPPER(description) LIKE '%VENTLINE%'
       OR UPPER(description) LIKE '%PRE OWNED VENT%'
       OR UPPER(description) LIKE '%RVLOVENT%'
       OR UPPER(description) LIKE '%RANGE COVER%'
  );

-- → ELECTRICAL
UPDATE inventory SET category = 'ELECTRICAL', updated_at = NOW()
WHERE category = 'MISC/SHOP SUPPLIES'
  AND (
       UPPER(description) LIKE '%WIRE %'
       OR UPPER(description) LIKE '%WIRING%'
       OR UPPER(description) LIKE '%FUSE%'
       OR UPPER(description) LIKE '%BREAKER%'
       OR UPPER(description) LIKE '%CIRCUIT BOARD%'
       OR UPPER(description) LIKE '%CONTROL BOARD%'
       OR UPPER(description) LIKE '%MAIN BOARD%'
       OR UPPER(description) LIKE '%RELAY%'
       OR UPPER(description) LIKE '%INVERTER%'
       OR UPPER(description) LIKE '%CONVERTER%'
       OR UPPER(description) LIKE '%BATTERY TERM%'
       OR UPPER(description) LIKE '%BULB%'
       OR UPPER(description) LIKE '%LED%'
       OR UPPER(description) LIKE '%VOLT%'
       OR UPPER(description) LIKE '%AMP BUSS%'
       OR UPPER(description) LIKE '%SUPER FUSE%'
       OR UPPER(description) LIKE '%TRAILER PLUG%'
       OR UPPER(description) LIKE '%POWER INLET%'
       OR UPPER(description) LIKE '%ELECTRODE%'
       OR UPPER(description) LIKE '%IGNITER%'
       OR UPPER(description) LIKE '%BRAKE CONT%'
       OR UPPER(description) LIKE '%BREAKAWAY%'
       OR UPPER(description) LIKE '%BRAKE-A-WAY%'
       OR UPPER(description) LIKE '%HEATER SWITCH%'
       OR UPPER(description) LIKE '%ILLUMINATED%'
       OR UPPER(description) LIKE '%THERMOSTAT%'
       OR UPPER(description) LIKE '%USB CHARGER%'
       OR UPPER(description) LIKE '%ROMEX%'
       OR UPPER(description) LIKE '%HEAT SHRINK%'
       OR UPPER(description) LIKE '%SHRINK TUBING%'
       OR UPPER(description) LIKE '%SCOTCH LOK%'
       OR UPPER(description) LIKE '%TERMINAL %'
       OR UPPER(description) LIKE '%SPADE QUICK%'
       OR UPPER(description) LIKE '%NYLON SPADE%'
       OR UPPER(description) LIKE '%JUNCTION BOX%'
       OR UPPER(description) LIKE '%JUCTION BOX%'
       OR UPPER(description) LIKE '%FLEX CONDUIT%'
       OR UPPER(description) LIKE '%CAT6%'
       OR UPPER(description) LIKE '%CAT 8%'
       OR UPPER(description) LIKE '%ETHERNET%'
       OR UPPER(description) LIKE '%HDMI%'
       OR UPPER(description) LIKE '%USB EXTENSION%'
       OR UPPER(description) LIKE '%COOLING FAN%'
       OR UPPER(description) LIKE '%WEBOOST%'
       OR UPPER(description) LIKE '%WE BOOST%'
       OR UPPER(description) LIKE '%WINEGARD ANTENNA%'
       OR UPPER(description) LIKE '%AIR 360%'
       OR UPPER(description) LIKE '%STARLINK%'
       OR UPPER(description) LIKE '%FURRION VISION%'
       OR UPPER(description) LIKE '%BACKUP CAMERA%'
       OR UPPER(description) LIKE '%MARKER LIGHT%'
       OR UPPER(description) LIKE '%CLEARANCE LIGHT%'
       OR UPPER(description) LIKE '%RED MARKER%'
       OR UPPER(description) LIKE '%INTERIOR CHARGING%'
       OR UPPER(description) LIKE '%WALL MOUNT USB%'
       OR UPPER(description) LIKE '%CHARGING PORT%'
       OR UPPER(description) LIKE '%POWER CORD ADAPT%'
       OR UPPER(description) LIKE '%ADAPTER CORD 30%'
       OR UPPER(description) LIKE '%MICRO AIR EASY START%'
       OR UPPER(description) LIKE '%POWER REVERSING%'
       OR UPPER(description) LIKE '%SENSOR PROBE%'
       OR UPPER(description) LIKE '%SENDING UNIT%'
       OR UPPER(description) LIKE '%TANK PROB%'
       OR UPPER(description) LIKE '%CONDUCTOR CORD%'
       OR UPPER(description) LIKE '%7-WAY TRAILER CORD%'
       OR UPPER(description) LIKE '%TRAILER CORD%'
       OR UPPER(description) LIKE '%PARALLAX POWER%'
       OR UPPER(description) LIKE '%BATTERY BOX%'
       OR UPPER(description) LIKE '%ENGINE BATTERY%'
       OR UPPER(description) LIKE '%MOTORCYCLE BATTERY%'
       OR UPPER(description) LIKE '%LEAD ACID BATTERY%'
       OR UPPER(description) LIKE '%NON-HAZARDOUS BATTERY%'
       OR UPPER(description) LIKE '%BATTERY LUG%'
       OR UPPER(description) LIKE '%COPPER LUG%'
       OR UPPER(description) LIKE '%LOOM KIT%'
       OR UPPER(description) LIKE '%HARNESS%'
       OR UPPER(description) LIKE '%DIMMER%'
       OR UPPER(description) LIKE '%MONITOR PANEL%'
       OR UPPER(description) LIKE '%GFCI%'
       OR UPPER(description) LIKE '%GFI%'
       OR UPPER(description) LIKE '%GROMMET%'
       OR UPPER(description) LIKE '%ZIP TIE%'
       OR UPPER(description) LIKE '%TIE BASE%'
       OR UPPER(description) LIKE '%SCOTCH LOKS%'
       OR UPPER(description) LIKE '%INSULATED CLAMP%'
       OR UPPER(description) LIKE '%12V. BRAKE%'
       OR UPPER(description) LIKE '%INLET 50A%'
       OR UPPER(description) LIKE '%FACE PLATE%'
       OR UPPER(description) LIKE '%PUSH ON-PUS%'
       OR UPPER(description) LIKE '%USB CHARGE PORT%'
       OR UPPER(description) LIKE '%PLATE POWER SUPPLY%'
       OR UPPER(description) LIKE '%BRAKE AND TURN%'
       OR UPPER(description) LIKE '%SPOT LIGHT%'
       OR UPPER(description) LIKE '%20 FT 12V%'
       OR UPPER(description) LIKE '%LP DETECTOR%'
       OR UPPER(description) LIKE '%30 SERIES LP DET%'
  );

-- → PLUMBING
UPDATE inventory SET category = 'PLUMBING', updated_at = NOW()
WHERE category = 'MISC/SHOP SUPPLIES'
  AND (
       UPPER(description) LIKE '%WATER VALVE%'
       OR UPPER(description) LIKE '%WATER PUMP%'
       OR UPPER(description) LIKE '%WATER HEATER%'
       OR UPPER(description) LIKE '%WATER TANK%'
       OR UPPER(description) LIKE '%WATER FLANGE%'
       OR UPPER(description) LIKE '%WATER TREATMENT%'
       OR UPPER(description) LIKE '%WATER SHOCK%'
       OR UPPER(description) LIKE '%FRESH WATER%'
       OR UPPER(description) LIKE '%CITY WATER%'
       OR UPPER(description) LIKE '%CITY/TANK FILL%'
       OR UPPER(description) LIKE '%SEWER%'
       OR UPPER(description) LIKE '%TOILET%'
       OR UPPER(description) LIKE '%FAUCET%'
       OR UPPER(description) LIKE '%SHOWER%'
       OR UPPER(description) LIKE '%DRAIN%'
       OR UPPER(description) LIKE '%STRAINER%'
       OR UPPER(description) LIKE '%ANODE ROD%'
       OR UPPER(description) LIKE '%MIXING VALVE%'
       OR UPPER(description) LIKE '%VACUUM BREAKER%'
       OR UPPER(description) LIKE '%TERMINATION CAP%'
       OR UPPER(description) LIKE '%ANTIFREEZE%'
       OR UPPER(description) LIKE '%FLUSH VALVE%'
       OR UPPER(description) LIKE '%PEX%'
       OR UPPER(description) LIKE '%P-TRAP%'
       OR UPPER(description) LIKE '%P TRAP%'
       OR UPPER(description) LIKE '%PTRAP%'
       OR UPPER(description) LIKE '%ABS P%'
       OR UPPER(description) LIKE '%PVC PIPE%'
       OR UPPER(description) LIKE '%PVC REDUCER%'
       OR UPPER(description) LIKE '%BARB FITTING%'
       OR UPPER(description) LIKE '%HOSE CLAMP%'
       OR UPPER(description) LIKE '%PINCH CLAMP%'
       OR UPPER(description) LIKE '%BRASS TEE%'
       OR UPPER(description) LIKE '%BRASS ADAPTER%'
       OR UPPER(description) LIKE '%BRASS TUBE FIT%'
       OR UPPER(description) LIKE '%COMPRESSION FIT%'
       OR UPPER(description) LIKE '%FIP BRASS%'
       OR UPPER(description) LIKE '%MALE ADAPTER%'
       OR UPPER(description) LIKE '%FEMALE ADAPTER%'
       OR UPPER(description) LIKE '%FNPT%'
       OR UPPER(description) LIKE '% NPT %'
       OR UPPER(description) LIKE '%SWIVEL FEMALE%'
       OR UPPER(description) LIKE '%ELBOW FIT%'
       OR UPPER(description) LIKE '%TEE FIT%'
       OR UPPER(description) LIKE '%UNION FLAIR%'
       OR UPPER(description) LIKE '%FLARE UNION%'
       OR UPPER(description) LIKE '%REDUCING ADAPTER%'
       OR UPPER(description) LIKE '%PEX FITTING%'
       OR UPPER(description) LIKE '%PEX CLAMP%'
       OR UPPER(description) LIKE '%SHARKBITE%'
       OR UPPER(description) LIKE '%FILL HOSE%'
       OR UPPER(description) LIKE '%FRESH TANK FILL%'
       OR UPPER(description) LIKE '%COPPER TUBE FLEX%'
       OR UPPER(description) LIKE '%SILICONE TUBE%'
       OR UPPER(description) LIKE '%PVC CEMENT%'
       OR UPPER(description) LIKE '%ABS CEMENT%'
       OR UPPER(description) LIKE '%VALTERRA%'
       OR UPPER(description) LIKE '%DRAIN VALVE%'
       OR UPPER(description) LIKE '%BASKET STRAINER%'
       OR UPPER(description) LIKE '%SINK BASKET%'
       OR UPPER(description) LIKE '%SINK SPRAYER%'
       OR UPPER(description) LIKE '%PLUMBING VENT%'
       OR UPPER(description) LIKE '%AQUA MAGIC%'
       OR UPPER(description) LIKE '%AQUA MAJIC%'
       OR UPPER(description) LIKE '%THETFORD%'
       OR UPPER(description) LIKE '%PROPANE HOSE%'
       OR UPPER(description) LIKE '%PIGTAIL HOSE%'
       OR UPPER(description) LIKE '%LP HOSE%'
       OR UPPER(description) LIKE '%LP PIGTAIL%'
       OR UPPER(description) LIKE '%PROPANE REGUL%'
       OR UPPER(description) LIKE '%LP REGUL%'
       OR UPPER(description) LIKE '%GAS REGUL%'
       OR UPPER(description) LIKE '%CHANGEOVER REG%'
       OR UPPER(description) LIKE '%AUTO CHANGE%'
       OR UPPER(description) LIKE '%TWO STAGE PROP%'
       OR UPPER(description) LIKE '%MEGR%'
       OR UPPER(description) LIKE '%ATKKE%'
       OR UPPER(description) LIKE '%PROPANE TANK%'
       OR UPPER(description) LIKE '%LP TANK%'
       OR UPPER(description) LIKE '%20LB TRAY%'
       OR UPPER(description) LIKE '%GAS STRUT%'
       OR UPPER(description) LIKE '%SOAP DISPENSER%'
       OR UPPER(description) LIKE '%SWIVEL ELBOW%'
       OR UPPER(description) LIKE '%90 DEGREE ELBOW%'
       OR UPPER(description) LIKE '%ABS ELBOW%'
       OR UPPER(description) LIKE '%ABS SHORT SWEEP%'
       OR UPPER(description) LIKE '%LONG SWEEP%'
       OR UPPER(description) LIKE '%ANODEROD%'
       OR UPPER(description) LIKE '%PENTAIR SHURFLO%'
       OR UPPER(description) LIKE '%1/4 MALE PIPE%'
       OR UPPER(description) LIKE '%PIPE CAP BRASS%'
       OR UPPER(description) LIKE '%STRAIGHT PIPE%'
       OR UPPER(description) LIKE '%UNIVERSAL L-MOUNT REGUL%'
       OR UPPER(description) LIKE '%CITY TANK FILL%'
       OR UPPER(description) LIKE '%RECPRO RV TANK%'
       OR UPPER(description) LIKE '%P-FITTINGS%'
       OR UPPER(description) LIKE '%NTP TO CLAMP%'
       OR UPPER(description) LIKE '%FLAIR 1/2%'
       OR UPPER(description) LIKE '%FITTING ABS%'
       OR UPPER(description) LIKE '%90 DEGREE END CAP%'
       OR UPPER(description) LIKE '%1 1/4" STRAIGHT%'
       OR UPPER(description) LIKE '%LFA-165 UNION%'
       OR UPPER(description) LIKE '%TANK REPAIR%'
       OR UPPER(description) LIKE '%QUIKSTEEL%'
       OR UPPER(description) LIKE '%HOLDING TANK PATCH%'
  );

-- → ROOFING
UPDATE inventory SET category = 'ROOFING', updated_at = NOW()
WHERE category = 'MISC/SHOP SUPPLIES'
  AND (
       UPPER(description) LIKE '%ROOF%'
       OR UPPER(description) LIKE '%DICOR%'
       OR UPPER(description) LIKE '%ADSEAL%'
       OR UPPER(description) LIKE '%SEALANT%'
       OR UPPER(description) LIKE '%SKYLIGHT%'
       OR UPPER(description) LIKE '%SKY LIGHT%'
       OR UPPER(description) LIKE '%RUBBER SEAL%'
       OR UPPER(description) LIKE '%WEDGE SEAL%'
       OR UPPER(description) LIKE '%FLANGE SEAL%'
       OR UPPER(description) LIKE '%CAULK%'
       OR UPPER(description) LIKE '%LAP SEALANT%'
       OR UPPER(description) LIKE '%BUTYL%'
       OR UPPER(description) LIKE '%ETERNABOND%'
       OR UPPER(description) LIKE '%GEOCEL%'
       OR UPPER(description) LIKE '%MEMBRANE%'
       OR UPPER(description) LIKE '%3M FASTBOND%'
       OR UPPER(description) LIKE '%CONTACT CEMENT%'
       OR UPPER(description) LIKE '%SIKAFLEX%'
       OR UPPER(description) LIKE '%RAPID SEAL%'
       OR UPPER(description) LIKE '%RUBBERIZED COATING%'
       OR UPPER(description) LIKE '%ROCK GUARD%'
       OR UPPER(description) LIKE '%STONE GUARD%'
       OR UPPER(description) LIKE '%RAIN GUTTER%'
       OR UPPER(description) LIKE '%GUTTER SPOUT%'
       OR UPPER(description) LIKE '%DURAPATCH%'
       OR UPPER(description) LIKE '%UNDERBELLY%'
       OR UPPER(description) LIKE '%BELLY BOTTOM%'
       OR UPPER(description) LIKE '%JWRAP SKIRT%'
       OR UPPER(description) LIKE '%GRAY BUTLY%'
       OR UPPER(description) LIKE '%HTTMT%'
       OR UPPER(description) LIKE '%IMPACT-RES%'
  );

-- → DOORS/WINDOWS/AWNINGS
UPDATE inventory SET category = 'DOORS/WINDOWS/AWNINGS', updated_at = NOW()
WHERE category = 'MISC/SHOP SUPPLIES'
  AND (
       UPPER(description) LIKE '%AWNING FABRIC%'
       OR UPPER(description) LIKE '%CAREFREE AWNING%'
       OR UPPER(description) LIKE '%SOLERA%'
       OR UPPER(description) LIKE '%SLIDE TOPPER%'
       OR UPPER(description) LIKE '%SLIDE ROOM%'
       OR UPPER(description) LIKE '%SLIDEOUT%'
       OR UPPER(description) LIKE '%SCHWINTEK%'
       OR UPPER(description) LIKE '%LIPPERT SLIDE%'
       OR UPPER(description) LIKE '%SLIDE MOTOR%'
       OR UPPER(description) LIKE '%SLIDE DRIVE%'
       OR UPPER(description) LIKE '%GEAR MOTOR SLIDE%'
       OR UPPER(description) LIKE '%ACCUE SLIDE%'
       OR UPPER(description) LIKE '%H TRACK%'
       OR UPPER(description) LIKE '%H-COLUMN%'
       OR UPPER(description) LIKE '%SLIDE FABRIC%'
       OR UPPER(description) LIKE '%TOPPER FABRIC%'
       OR UPPER(description) LIKE '%TOPPER SPRING%'
       OR UPPER(description) LIKE '%WINDOW KNOB%'
       OR UPPER(description) LIKE '%THUMB COMPARTMENT%'
       OR UPPER(description) LIKE '%KEYED COMPARTMENT%'
       OR UPPER(description) LIKE '%DOUBLE ROLLER CATCH%'
       OR UPPER(description) LIKE '%BULL DOG CATCH%'
       OR UPPER(description) LIKE '%DRAWER SLIDE SOCKET%'
       OR UPPER(description) LIKE '%GRABBER CATCHES%'
       OR UPPER(description) LIKE '%ANGLED T-STYLE%'
       OR UPPER(description) LIKE '%DRAWER SLIDE%'
       OR UPPER(description) LIKE '%CLAW BAR%'
       OR UPPER(description) LIKE '%SMOKED VENT LID%'
       OR UPPER(description) LIKE '%WHITE VENT LID%'
       OR UPPER(description) LIKE '%BVD0449%'
       OR UPPER(description) LIKE '%SKYLIGHT INNER%'
       OR UPPER(description) LIKE '%RADIUS CORNER 14X14%'
       OR UPPER(description) LIKE '%STEP LIPPERT%'
       OR UPPER(description) LIKE '%TORKLIFT%'
       OR UPPER(description) LIKE '%KWIKEE STEP%'
       OR UPPER(description) LIKE '%AIRSTREAM DOUBLE STEP%'
       OR UPPER(description) LIKE '%BLACK LEFT MOUNT STEP%'
       OR UPPER(description) LIKE '%WINDSHIELD TRIANGLE%'
       OR UPPER(description) LIKE '%PRIVACY GLASS%'
       OR UPPER(description) LIKE '%MEDICINE CABINET%'
       OR UPPER(description) LIKE '%TOWEL RING%'
       OR UPPER(description) LIKE '%INNER ARMS%'
       OR UPPER(description) LIKE '%OUTER ARMS%'
       OR UPPER(description) LIKE '%GEARPACKS%'
       OR UPPER(description) LIKE '%SATIN CASE SLATS%'
       OR UPPER(description) LIKE '%SPRING EYE BUSHING%'
       OR UPPER(description) LIKE '%RAFTER COLLAR%'
       OR UPPER(description) LIKE '%RETAINER SPLINE%'
       OR UPPER(description) LIKE '%ASCENT CVR%'
       OR UPPER(description) LIKE '%76_ ASCENT%'
       OR UPPER(description) LIKE '%RECPRO SKLIGHT%'
       OR UPPER(description) LIKE '%SCT RV SKILIGHT%'
       OR UPPER(description) LIKE '%SHADE/SCREEN%'
       OR UPPER(description) LIKE '%LARGE HATCH%'
       OR UPPER(description) LIKE '%KTN 8%'
       OR UPPER(description) LIKE '%SHW 4%'
  );

-- → TOWING/CHASSIS
UPDATE inventory SET category = 'TOWING/CHASSIS', updated_at = NOW()
WHERE category = 'MISC/SHOP SUPPLIES'
  AND (
       UPPER(description) LIKE '%AXLE%'
       OR UPPER(description) LIKE '%BRAKE ASSEMBL%'
       OR UPPER(description) LIKE '%BRAKE MAGNET%'
       OR UPPER(description) LIKE '%BRAKE PLATE%'
       OR UPPER(description) LIKE '%HUB%'
       OR UPPER(description) LIKE '%DRUM%'
       OR UPPER(description) LIKE '%BEARING%'
       OR UPPER(description) LIKE '%WHEEL SEAL%'
       OR UPPER(description) LIKE '%HITCH%'
       OR UPPER(description) LIKE '%BALL%'
       OR UPPER(description) LIKE '%COUPLER%'
       OR UPPER(description) LIKE '%TRAILER JACK%'
       OR UPPER(description) LIKE '%JACK BASE%'
       OR UPPER(description) LIKE '%JACK CRANK%'
       OR UPPER(description) LIKE '%DEXTER%'
       OR UPPER(description) LIKE '%ELECTRIC BRAKE%'
       OR UPPER(description) LIKE '%WEAR TABS%'
       OR UPPER(description) LIKE '%FIFTH WHEEL%'
       OR UPPER(description) LIKE '%LUBE PLATE%'
       OR UPPER(description) LIKE '%TIMKIN%'
       OR UPPER(description) LIKE '%TIMKEN%'
       OR UPPER(description) LIKE '%WHEEL WELL%'
       OR UPPER(description) LIKE '%BRAKLEEN%'
       OR UPPER(description) LIKE '%BRAKE CLEAN%'
       OR UPPER(description) LIKE '%DENCO BRAKE%'
       OR UPPER(description) LIKE '%HEATER HOSE%'
       OR UPPER(description) LIKE '%EXHAUST HANGER%'
       OR UPPER(description) LIKE '%SHOCK ABSORB%'
       OR UPPER(description) LIKE '%EQUALIZER%'
       OR UPPER(description) LIKE '%SWAY CONTROL%'
       OR UPPER(description) LIKE '%WEIGHT DIST%'
       OR UPPER(description) LIKE '%SPRING LEAF%'
       OR UPPER(description) LIKE '%LEAF SPRING%'
       OR UPPER(description) LIKE '%SAFETY CHAIN%'
       OR UPPER(description) LIKE '%SAFTY CHAIN%'
       OR UPPER(description) LIKE '%ALUMINUM WHEEL%'
       OR UPPER(description) LIKE '%RIM %'
       OR UPPER(description) LIKE '%FENDER SKIRT%'
       OR UPPER(description) LIKE '%PICK-UP TRUCK COVER%'
       OR UPPER(description) LIKE '%UNIVERSAL JOINT%'
       OR UPPER(description) LIKE '%EQ SYSTEMS CROSS BAR%'
       OR UPPER(description) LIKE '%MORRYDE%'
       OR UPPER(description) LIKE '%TANDEM WET KIT%'
       OR UPPER(description) LIKE '%TONGUE WEIGHT%'
       OR UPPER(description) LIKE '%TRAILER TONGUE BATTERY BOX%'
  );

-- → HARDWARE
UPDATE inventory SET category = 'HARDWARE', updated_at = NOW()
WHERE category = 'MISC/SHOP SUPPLIES'
  AND (
       UPPER(description) LIKE '%SCREW%'
       OR UPPER(description) LIKE '%BOLT %'
       OR UPPER(description) LIKE '%NUT %'
       OR UPPER(description) LIKE '%WASHER%'
       OR UPPER(description) LIKE '%RIVET%'
       OR UPPER(description) LIKE '%L BRACKET%'
       OR UPPER(description) LIKE '%CORNER BRACE%'
       OR UPPER(description) LIKE '%SS CLAMP%'
       OR UPPER(description) LIKE '%STIFFNER%'
       OR UPPER(description) LIKE '%MARINE COT%'
       OR UPPER(description) LIKE '%MOLDING%'
       OR UPPER(description) LIKE '%EXTRUSION%'
       OR UPPER(description) LIKE '%METAL SHEET%'
       OR UPPER(description) LIKE '%METAL SKIRT%'
       OR UPPER(description) LIKE '%BELTLINE%'
       OR UPPER(description) LIKE '%RUB RAIL%'
       OR UPPER(description) LIKE '%RUBRAIL%'
       OR UPPER(description) LIKE '%CHROME INSERT%'
       OR UPPER(description) LIKE '%AIRSTREAM SEGMENT%'
       OR UPPER(description) LIKE '%JAYCO DECAL%'
       OR UPPER(description) LIKE '%ANGLE IRON%'
       OR UPPER(description) LIKE '%FRONT METAL%'
       OR UPPER(description) LIKE '%ALUMINUM SHEET%'
       OR UPPER(description) LIKE '%ALUMINUM LOWER%'
       OR UPPER(description) LIKE '%ALUMINUM SIDE%'
       OR UPPER(description) LIKE '%AIRSTREAM CENTER%'
       OR UPPER(description) LIKE '%AIRSTREAM UPPER%'
       OR UPPER(description) LIKE '%AIRSTREAM REAR%'
       OR UPPER(description) LIKE '%BANANA WRAP%'
       OR UPPER(description) LIKE '%REAR CS SKIRT%'
       OR UPPER(description) LIKE '%FASCIA%'
       OR UPPER(description) LIKE '%NO-BO%'
       OR UPPER(description) LIKE '%NOBO%'
       OR UPPER(description) LIKE '%FRONT WALL%'
       OR UPPER(description) LIKE '%BROWN METAL%'
       OR UPPER(description) LIKE '%RED ROSIN PAPER%'
       OR UPPER(description) LIKE '%LAUAN%'
       OR UPPER(description) LIKE '%SANDE PLYWOOD%'
       OR UPPER(description) LIKE '%CARPET TILE%'
       OR UPPER(description) LIKE '%VELCRO%'
       OR UPPER(description) LIKE '%WIDE FLEX KEY%'
       OR UPPER(description) LIKE '%FLEX KEY%'
       OR UPPER(description) LIKE '%STAPLE%'
       OR UPPER(description) LIKE '%CROWN STAPLE%'
       OR UPPER(description) LIKE '%REFLEXIVE INSULATION%'
       OR UPPER(description) LIKE '%ECOBATT INSULATION%'
       OR UPPER(description) LIKE '%FOAM INSULATION%'
       OR UPPER(description) LIKE '%CLOROPLAST%'
       OR UPPER(description) LIKE '%PLASTIC TRAY%'
       OR UPPER(description) LIKE '%TRAY LINER%'
       OR UPPER(description) LIKE '%SPRING PIN%'
       OR UPPER(description) LIKE '%SPLIT SPRING%'
       OR UPPER(description) LIKE '%STUDS %'
       OR UPPER(description) LIKE '%PANEL 22.50%'
       OR UPPER(description) LIKE '%PRE LAMINATE%'
       OR UPPER(description) LIKE '%BLACK FOOT INSERT%'
       OR UPPER(description) LIKE '%LIP INSERT%'
       OR UPPER(description) LIKE '%LEG INSERT%'
       OR UPPER(description) LIKE '%VINYL CAP BASE%'
       OR UPPER(description) LIKE '%VINYL INSERT%'
       OR UPPER(description) LIKE '%D SEAL %'
       OR UPPER(description) LIKE '%3/8-16 X 3.50%'
       OR UPPER(description) LIKE '%METAL MAGERY%'
       OR UPPER(description) LIKE '%NARROW BODY BOW%'
       OR UPPER(description) LIKE '%SUPPORT BRACE LOWER%'
       OR UPPER(description) LIKE '%UPPER ROADSIDE SHEET%'
       OR UPPER(description) LIKE '%FLAT METAL RADIUS%'
       OR UPPER(description) LIKE '%ALTERNATIVE PA%'
       OR UPPER(description) LIKE '%EPOXY BLACK%'
       OR UPPER(description) LIKE '%RESEN APPOXY%'
       OR UPPER(description) LIKE '%VINAL ROUND BUMPER%'
       OR UPPER(description) LIKE '%SOAP DISPENSER%'
       OR UPPER(description) LIKE '%4" C CLAMP%'
       OR UPPER(description) LIKE '%1 INCH BLACK VINYL%'
       OR UPPER(description) LIKE '%ANG 1.5 X%'
       OR UPPER(description) LIKE '%ARCTIC CENTER RADIUS%'
       OR UPPER(description) LIKE '%TITAN SLEEVE%'
       OR UPPER(description) LIKE '%STREAMLINE SQUARED%'
       OR UPPER(description) LIKE '%STEEL BATTERY BOX%'
       OR UPPER(description) LIKE '%BATTERY BOX GROUP%'
       OR UPPER(description) LIKE '%BATTERY BOX - DOUBLE%'
       OR UPPER(description) LIKE '%22" W STEEL BATTERY%'
       OR UPPER(description) LIKE '%STEEL BATTERY%'
       OR UPPER(description) LIKE '%5/16 GROMET%'
       OR UPPER(description) LIKE '%CLAMPS %'
       OR UPPER(description) LIKE '%SS TEKS%'
       OR UPPER(description) LIKE '%3/4 SPLIT%'
       OR UPPER(description) LIKE '%INSULATED 1" CLAMP%'
       OR UPPER(description) LIKE '%FACE PLATE%'
       OR UPPER(description) LIKE '%PUSH ON-PUS%'
       OR UPPER(description) LIKE '%1.16TH INCH METAL CABLE%'
       OR UPPER(description) LIKE '%GIG%'
       OR UPPER(description) LIKE '%WIDGET%'
  );

COMMIT;

-- Verify results:
-- SELECT category, COUNT(*) FROM inventory GROUP BY category ORDER BY category;