-- ================================================================
-- Inventory category cleanup v2
-- 1. Merges short codes into full names
-- 2. Re-categorizes MISC/SHOP SUPPLIES items by keyword
-- 3. Adds AIRSTREAM as its own category
-- ================================================================

BEGIN;

-- STEP 1: Normalize short category codes to full names

UPDATE inventory SET category = 'ELECTRICAL', updated_at = NOW() WHERE category = 'ELEC';
UPDATE inventory SET category = 'PLUMBING', updated_at = NOW() WHERE category = 'PLMB';
UPDATE inventory SET category = 'HARDWARE', updated_at = NOW() WHERE category = 'HDWR';
UPDATE inventory SET category = 'ROOFING', updated_at = NOW() WHERE category = 'ROOF';
UPDATE inventory SET category = 'DOORS/WINDOWS/AWNINGS', updated_at = NOW() WHERE category = 'DOOR';
UPDATE inventory SET category = 'SOLAR', updated_at = NOW() WHERE category = 'SOLR';
UPDATE inventory SET category = 'TOWING/CHASSIS', updated_at = NOW() WHERE category = 'TOW';
UPDATE inventory SET category = 'HVAC', updated_at = NOW() WHERE category = 'HVAC';
UPDATE inventory SET category = 'MISC/SHOP SUPPLIES', updated_at = NOW() WHERE category = 'MISC';

-- STEP 2: Re-categorize items incorrectly in MISC/SHOP SUPPLIES

-- → SOLAR
UPDATE inventory SET category = 'SOLAR', updated_at = NOW()
WHERE category = 'MISC/SHOP SUPPLIES'
  AND (
       UPPER(name) LIKE '%SOLAR%'
       OR UPPER(name) LIKE '%RENOGY%'
       OR UPPER(name) LIKE '%VICTRON%'
       OR UPPER(name) LIKE '%LITHIUM%'
       OR UPPER(name) LIKE '%LIFEPO4%'
       OR UPPER(name) LIKE '%BATTLEBORN%'
       OR UPPER(name) LIKE '%EPOCH 300%'
       OR UPPER(name) LIKE '%SMARTSHUNT%'
       OR UPPER(name) LIKE '%MULTIPLUS%'
       OR UPPER(name) LIKE '%DC TO DC CHARG%'
       OR UPPER(name) LIKE '%MPPT%'
       OR UPPER(name) LIKE '%CHARGE CONTROL%'
       OR UPPER(name) LIKE '%SHADOWFLUX%'
       OR UPPER(name) LIKE '%ZAMP%'
       OR UPPER(name) LIKE '%GOPOWER%'
       OR UPPER(name) LIKE '%PULSE WAVE%'
       OR UPPER(name) LIKE '%HEAT BATTERY%'
       OR UPPER(name) LIKE '%AGM BATTERY%'
       OR UPPER(name) LIKE '%DEEP CYCLE%'
       OR UPPER(name) LIKE '%GROUP 24%'
       OR UPPER(name) LIKE '%GROUP 27%'
       OR UPPER(name) LIKE '%BUSBAR%'
       OR UPPER(name) LIKE '%BUS BAR%'
       OR UPPER(name) LIKE '%300AMP%'
       OR UPPER(name) LIKE '%BATTERY LUG%'
       OR UPPER(name) LIKE '%BATTER LUG%'
       OR UPPER(name) LIKE '%COPPER LUG%'
       OR UPPER(name) LIKE '%WELDING CABLE%'
       OR UPPER(name) LIKE '%WELDING CAB%'
       OR UPPER(name) LIKE '%AWG%'
       OR UPPER(name) LIKE '%1/0 GAUGE%'
       OR UPPER(name) LIKE '%2/0 GAUGE%'
       OR UPPER(name) LIKE '%4/0 GAUGE%'
       OR UPPER(name) LIKE '%FLEXAPRENE%'
       OR UPPER(name) LIKE '%BATTERY JUMP%'
       OR UPPER(name) LIKE '%JUMP STARTER%'
  );

-- → HVAC
UPDATE inventory SET category = 'HVAC', updated_at = NOW()
WHERE category = 'MISC/SHOP SUPPLIES'
  AND (
       UPPER(name) LIKE '%FURNACE%'
       OR UPPER(name) LIKE '%ATWOOD%'
       OR UPPER(name) LIKE '%DOMETIC HEAT%'
       OR UPPER(name) LIKE '%DOMETIC FRESH%'
       OR UPPER(name) LIKE '%COLEMAN MACH%'
       OR UPPER(name) LIKE '%COLEMAN-MACH%'
       OR UPPER(name) LIKE '%MAXXFAN%'
       OR UPPER(name) LIKE '%MAXX AIR%'
       OR UPPER(name) LIKE '%SAIL SWITCH%'
       OR UPPER(name) LIKE '%HEATING ELEMENT%'
       OR UPPER(name) LIKE '%THERMAL CUT%'
       OR UPPER(name) LIKE '%COOKTOP%'
       OR UPPER(name) LIKE '%STOVE BURN%'
       OR UPPER(name) LIKE '%REFRIGERANT%'
       OR UPPER(name) LIKE '%PENGUIN%'
       OR UPPER(name) LIKE '%PENQUIN%'
       OR UPPER(name) LIKE '%BRISK AIR%'
       OR UPPER(name) LIKE '%FRESH JET%'
       OR UPPER(name) LIKE '%MACH 8%'
       OR UPPER(name) LIKE '%MACH 15%'
       OR UPPER(name) LIKE '%AC MOUNTING%'
       OR UPPER(name) LIKE '%AC CEILING%'
       OR UPPER(name) LIKE '%AIR DISTRIBUTION%'
       OR UPPER(name) LIKE '%START RUN CAP%'
       OR UPPER(name) LIKE '%RANGE HOOD%'
       OR UPPER(name) LIKE '%BARALDI%'
       OR UPPER(name) LIKE '%FAN BLADE%'
       OR UPPER(name) LIKE '%VENT FAN MOTOR%'
       OR UPPER(name) LIKE '%FANTASTIC FAN%'
       OR UPPER(name) LIKE '%BATHROOM VENT FAN%'
       OR UPPER(name) LIKE '%EXHAUST FAN 14%'
       OR UPPER(name) LIKE '%WHITE DOME ASSEMBLY%'
       OR UPPER(name) LIKE '%VENT LID%'
       OR UPPER(name) LIKE '%SMOKE DOME%'
       OR UPPER(name) LIKE '%MAXXAIR VENT%'
       OR UPPER(name) LIKE '%MAXXAIR SMOKED%'
       OR UPPER(name) LIKE '%AIR RETURN VENT%'
       OR UPPER(name) LIKE '%HEATING/COOLING REGISTER%'
       OR UPPER(name) LIKE '%REGISTER FLOOR%'
       OR UPPER(name) LIKE '%DOMETIC AIR GRILLE%'
       OR UPPER(name) LIKE '%HEKI%'
       OR UPPER(name) LIKE '%SHROUD%'
       OR UPPER(name) LIKE '%FURRION AC%'
       OR UPPER(name) LIKE '%RECPRO AC%'
       OR UPPER(name) LIKE '%NORCOLD%'
       OR UPPER(name) LIKE '%LP GAS ALARM%'
       OR UPPER(name) LIKE '%PROPANE DETECT%'
       OR UPPER(name) LIKE '%CO ALARM%'
       OR UPPER(name) LIKE '%SAFE T ALERT%'
       OR UPPER(name) LIKE '%DUAL LP%'
       OR UPPER(name) LIKE '%CARBON MONOXIDE%'
       OR UPPER(name) LIKE '%HOLDING TANK TREATMENT%'
       OR UPPER(name) LIKE '%DIGEST-IT%'
       OR UPPER(name) LIKE '%TANK TREATMENT%'
       OR UPPER(name) LIKE '%HOLDING TANK PATCH%'
       OR UPPER(name) LIKE '%GEN AIR FILTER%'
       OR UPPER(name) LIKE '%TAIL PIPE%'
       OR UPPER(name) LIKE '%EXHAUST CO%'
       OR UPPER(name) LIKE '%MOTOR 12V FUR%'
       OR UPPER(name) LIKE '%ROUND VENT 6%'
       OR UPPER(name) LIKE '%EXTERIOR VENT%'
       OR UPPER(name) LIKE '%GIRARD WATER HEATER%'
       OR UPPER(name) LIKE '%VENTLINE%'
       OR UPPER(name) LIKE '%PRE OWNED VENT%'
       OR UPPER(name) LIKE '%RVLOVENT%'
       OR UPPER(name) LIKE '%RANGE COVER%'
  );

-- → ELECTRICAL
UPDATE inventory SET category = 'ELECTRICAL', updated_at = NOW()
WHERE category = 'MISC/SHOP SUPPLIES'
  AND (
       UPPER(name) LIKE '%WIRE %'
       OR UPPER(name) LIKE '%WIRING%'
       OR UPPER(name) LIKE '%FUSE%'
       OR UPPER(name) LIKE '%BREAKER%'
       OR UPPER(name) LIKE '%CIRCUIT BOARD%'
       OR UPPER(name) LIKE '%CONTROL BOARD%'
       OR UPPER(name) LIKE '%MAIN BOARD%'
       OR UPPER(name) LIKE '%RELAY%'
       OR UPPER(name) LIKE '%INVERTER%'
       OR UPPER(name) LIKE '%CONVERTER%'
       OR UPPER(name) LIKE '%BATTERY TERM%'
       OR UPPER(name) LIKE '%BULB%'
       OR UPPER(name) LIKE '%LED%'
       OR UPPER(name) LIKE '%VOLT%'
       OR UPPER(name) LIKE '%AMP BUSS%'
       OR UPPER(name) LIKE '%SUPER FUSE%'
       OR UPPER(name) LIKE '%TRAILER PLUG%'
       OR UPPER(name) LIKE '%POWER INLET%'
       OR UPPER(name) LIKE '%ELECTRODE%'
       OR UPPER(name) LIKE '%IGNITER%'
       OR UPPER(name) LIKE '%BRAKE CONT%'
       OR UPPER(name) LIKE '%BREAKAWAY%'
       OR UPPER(name) LIKE '%BRAKE-A-WAY%'
       OR UPPER(name) LIKE '%HEATER SWITCH%'
       OR UPPER(name) LIKE '%ILLUMINATED%'
       OR UPPER(name) LIKE '%THERMOSTAT%'
       OR UPPER(name) LIKE '%USB CHARGER%'
       OR UPPER(name) LIKE '%ROMEX%'
       OR UPPER(name) LIKE '%HEAT SHRINK%'
       OR UPPER(name) LIKE '%SHRINK TUBING%'
       OR UPPER(name) LIKE '%SCOTCH LOK%'
       OR UPPER(name) LIKE '%TERMINAL %'
       OR UPPER(name) LIKE '%SPADE QUICK%'
       OR UPPER(name) LIKE '%NYLON SPADE%'
       OR UPPER(name) LIKE '%JUNCTION BOX%'
       OR UPPER(name) LIKE '%JUCTION BOX%'
       OR UPPER(name) LIKE '%FLEX CONDUIT%'
       OR UPPER(name) LIKE '%CAT6%'
       OR UPPER(name) LIKE '%CAT 8%'
       OR UPPER(name) LIKE '%ETHERNET%'
       OR UPPER(name) LIKE '%HDMI%'
       OR UPPER(name) LIKE '%USB EXTENSION%'
       OR UPPER(name) LIKE '%COOLING FAN%'
       OR UPPER(name) LIKE '%WEBOOST%'
       OR UPPER(name) LIKE '%WE BOOST%'
       OR UPPER(name) LIKE '%WINEGARD ANTENNA%'
       OR UPPER(name) LIKE '%AIR 360%'
       OR UPPER(name) LIKE '%STARLINK%'
       OR UPPER(name) LIKE '%FURRION VISION%'
       OR UPPER(name) LIKE '%BACKUP CAMERA%'
       OR UPPER(name) LIKE '%MARKER LIGHT%'
       OR UPPER(name) LIKE '%CLEARANCE LIGHT%'
       OR UPPER(name) LIKE '%RED MARKER%'
       OR UPPER(name) LIKE '%INTERIOR CHARGING%'
       OR UPPER(name) LIKE '%WALL MOUNT USB%'
       OR UPPER(name) LIKE '%CHARGING PORT%'
       OR UPPER(name) LIKE '%POWER CORD ADAPT%'
       OR UPPER(name) LIKE '%ADAPTER CORD 30%'
       OR UPPER(name) LIKE '%MICRO AIR EASY START%'
       OR UPPER(name) LIKE '%POWER REVERSING%'
       OR UPPER(name) LIKE '%SENSOR PROBE%'
       OR UPPER(name) LIKE '%SENDING UNIT%'
       OR UPPER(name) LIKE '%TANK PROB%'
       OR UPPER(name) LIKE '%CONDUCTOR CORD%'
       OR UPPER(name) LIKE '%7-WAY TRAILER CORD%'
       OR UPPER(name) LIKE '%TRAILER CORD%'
       OR UPPER(name) LIKE '%PARALLAX POWER%'
       OR UPPER(name) LIKE '%BATTERY BOX%'
       OR UPPER(name) LIKE '%ENGINE BATTERY%'
       OR UPPER(name) LIKE '%MOTORCYCLE BATTERY%'
       OR UPPER(name) LIKE '%LEAD ACID BATTERY%'
       OR UPPER(name) LIKE '%NON-HAZARDOUS BATTERY%'
       OR UPPER(name) LIKE '%LOOM KIT%'
       OR UPPER(name) LIKE '%HARNESS%'
       OR UPPER(name) LIKE '%DIMMER%'
       OR UPPER(name) LIKE '%MONITOR PANEL%'
       OR UPPER(name) LIKE '%GROMMET%'
       OR UPPER(name) LIKE '%ZIP TIE%'
       OR UPPER(name) LIKE '%TIE BASE%'
       OR UPPER(name) LIKE '%SCOTCH LOKS%'
       OR UPPER(name) LIKE '%INSULATED CLAMP%'
       OR UPPER(name) LIKE '%12V. BRAKE%'
       OR UPPER(name) LIKE '%INLET 50A%'
       OR UPPER(name) LIKE '%FACE PLATE%'
       OR UPPER(name) LIKE '%PUSH ON-PUS%'
       OR UPPER(name) LIKE '%USB CHARGE PORT%'
       OR UPPER(name) LIKE '%PLATE POWER SUPPLY%'
       OR UPPER(name) LIKE '%BRAKE AND TURN%'
       OR UPPER(name) LIKE '%SPOT LIGHT%'
       OR UPPER(name) LIKE '%20 FT 12V%'
       OR UPPER(name) LIKE '%LP DETECTOR%'
  );

-- → PLUMBING
UPDATE inventory SET category = 'PLUMBING', updated_at = NOW()
WHERE category = 'MISC/SHOP SUPPLIES'
  AND (
       UPPER(name) LIKE '%WATER VALVE%'
       OR UPPER(name) LIKE '%WATER PUMP%'
       OR UPPER(name) LIKE '%WATER HEATER%'
       OR UPPER(name) LIKE '%WATER TANK%'
       OR UPPER(name) LIKE '%WATER FLANGE%'
       OR UPPER(name) LIKE '%WATER TREATMENT%'
       OR UPPER(name) LIKE '%WATER SHOCK%'
       OR UPPER(name) LIKE '%FRESH WATER%'
       OR UPPER(name) LIKE '%CITY WATER%'
       OR UPPER(name) LIKE '%CITY/TANK FILL%'
       OR UPPER(name) LIKE '%SEWER%'
       OR UPPER(name) LIKE '%TOILET%'
       OR UPPER(name) LIKE '%FAUCET%'
       OR UPPER(name) LIKE '%SHOWER%'
       OR UPPER(name) LIKE '%DRAIN%'
       OR UPPER(name) LIKE '%STRAINER%'
       OR UPPER(name) LIKE '%ANODE ROD%'
       OR UPPER(name) LIKE '%MIXING VALVE%'
       OR UPPER(name) LIKE '%VACUUM BREAKER%'
       OR UPPER(name) LIKE '%TERMINATION CAP%'
       OR UPPER(name) LIKE '%ANTIFREEZE%'
       OR UPPER(name) LIKE '%FLUSH VALVE%'
       OR UPPER(name) LIKE '%PEX%'
       OR UPPER(name) LIKE '%P-TRAP%'
       OR UPPER(name) LIKE '%P TRAP%'
       OR UPPER(name) LIKE '%PTRAP%'
       OR UPPER(name) LIKE '%ABS P%'
       OR UPPER(name) LIKE '%PVC PIPE%'
       OR UPPER(name) LIKE '%PVC REDUCER%'
       OR UPPER(name) LIKE '%BARB FITTING%'
       OR UPPER(name) LIKE '%HOSE CLAMP%'
       OR UPPER(name) LIKE '%PINCH CLAMP%'
       OR UPPER(name) LIKE '%BRASS TEE%'
       OR UPPER(name) LIKE '%BRASS ADAPTER%'
       OR UPPER(name) LIKE '%BRASS TUBE FIT%'
       OR UPPER(name) LIKE '%COMPRESSION FIT%'
       OR UPPER(name) LIKE '%FIP BRASS%'
       OR UPPER(name) LIKE '%MALE ADAPTER%'
       OR UPPER(name) LIKE '%FEMALE ADAPTER%'
       OR UPPER(name) LIKE '%FNPT%'
       OR UPPER(name) LIKE '% NPT %'
       OR UPPER(name) LIKE '%SWIVEL FEMALE%'
       OR UPPER(name) LIKE '%ELBOW FIT%'
       OR UPPER(name) LIKE '%TEE FIT%'
       OR UPPER(name) LIKE '%UNION FLAIR%'
       OR UPPER(name) LIKE '%FLARE UNION%'
       OR UPPER(name) LIKE '%REDUCING ADAPTER%'
       OR UPPER(name) LIKE '%PEX FITTING%'
       OR UPPER(name) LIKE '%PEX CLAMP%'
       OR UPPER(name) LIKE '%SHARKBITE%'
       OR UPPER(name) LIKE '%FILL HOSE%'
       OR UPPER(name) LIKE '%FRESH TANK FILL%'
       OR UPPER(name) LIKE '%COPPER TUBE FLEX%'
       OR UPPER(name) LIKE '%SILICONE TUBE%'
       OR UPPER(name) LIKE '%PVC CEMENT%'
       OR UPPER(name) LIKE '%ABS CEMENT%'
       OR UPPER(name) LIKE '%VALTERRA%'
       OR UPPER(name) LIKE '%DRAIN VALVE%'
       OR UPPER(name) LIKE '%BASKET STRAINER%'
       OR UPPER(name) LIKE '%SINK BASKET%'
       OR UPPER(name) LIKE '%SINK SPRAYER%'
       OR UPPER(name) LIKE '%PLUMBING VENT%'
       OR UPPER(name) LIKE '%AQUA MAGIC%'
       OR UPPER(name) LIKE '%AQUA MAJIC%'
       OR UPPER(name) LIKE '%THETFORD%'
       OR UPPER(name) LIKE '%PROPANE HOSE%'
       OR UPPER(name) LIKE '%PIGTAIL HOSE%'
       OR UPPER(name) LIKE '%LP HOSE%'
       OR UPPER(name) LIKE '%LP PIGTAIL%'
       OR UPPER(name) LIKE '%PROPANE REGUL%'
       OR UPPER(name) LIKE '%LP REGUL%'
       OR UPPER(name) LIKE '%GAS REGUL%'
       OR UPPER(name) LIKE '%CHANGEOVER REG%'
       OR UPPER(name) LIKE '%AUTO CHANGE%'
       OR UPPER(name) LIKE '%TWO STAGE PROP%'
       OR UPPER(name) LIKE '%MEGR%'
       OR UPPER(name) LIKE '%ATKKE%'
       OR UPPER(name) LIKE '%PROPANE TANK%'
       OR UPPER(name) LIKE '%LP TANK%'
       OR UPPER(name) LIKE '%20LB TRAY%'
       OR UPPER(name) LIKE '%GAS STRUT%'
       OR UPPER(name) LIKE '%SOAP DISPENSER%'
       OR UPPER(name) LIKE '%SWIVEL ELBOW%'
       OR UPPER(name) LIKE '%90 DEGREE ELBOW%'
       OR UPPER(name) LIKE '%ABS ELBOW%'
       OR UPPER(name) LIKE '%ABS SHORT SWEEP%'
       OR UPPER(name) LIKE '%LONG SWEEP%'
       OR UPPER(name) LIKE '%ANODEROD%'
       OR UPPER(name) LIKE '%PENTAIR SHURFLO%'
       OR UPPER(name) LIKE '%1/4 MALE PIPE%'
       OR UPPER(name) LIKE '%PIPE CAP BRASS%'
       OR UPPER(name) LIKE '%STRAIGHT PIPE%'
       OR UPPER(name) LIKE '%UNIVERSAL L-MOUNT REGUL%'
       OR UPPER(name) LIKE '%RECPRO RV TANK%'
       OR UPPER(name) LIKE '%P-FITTINGS%'
       OR UPPER(name) LIKE '%NTP TO CLAMP%'
       OR UPPER(name) LIKE '%FLAIR 1/2%'
       OR UPPER(name) LIKE '%FITTING ABS%'
       OR UPPER(name) LIKE '%90 DEGREE END CAP%'
       OR UPPER(name) LIKE '%LFA-165 UNION%'
       OR UPPER(name) LIKE '%TANK REPAIR%'
       OR UPPER(name) LIKE '%QUIKSTEEL%'
       OR UPPER(name) LIKE '%HOLDING TANK PATCH%'
  );

-- → ROOFING
UPDATE inventory SET category = 'ROOFING', updated_at = NOW()
WHERE category = 'MISC/SHOP SUPPLIES'
  AND (
       UPPER(name) LIKE '%ROOF%'
       OR UPPER(name) LIKE '%DICOR%'
       OR UPPER(name) LIKE '%ADSEAL%'
       OR UPPER(name) LIKE '%SEALANT%'
       OR UPPER(name) LIKE '%SKYLIGHT%'
       OR UPPER(name) LIKE '%SKY LIGHT%'
       OR UPPER(name) LIKE '%RUBBER SEAL%'
       OR UPPER(name) LIKE '%WEDGE SEAL%'
       OR UPPER(name) LIKE '%FLANGE SEAL%'
       OR UPPER(name) LIKE '%CAULK%'
       OR UPPER(name) LIKE '%LAP SEALANT%'
       OR UPPER(name) LIKE '%BUTYL%'
       OR UPPER(name) LIKE '%ETERNABOND%'
       OR UPPER(name) LIKE '%GEOCEL%'
       OR UPPER(name) LIKE '%MEMBRANE%'
       OR UPPER(name) LIKE '%3M FASTBOND%'
       OR UPPER(name) LIKE '%CONTACT CEMENT%'
       OR UPPER(name) LIKE '%SIKAFLEX%'
       OR UPPER(name) LIKE '%RAPID SEAL%'
       OR UPPER(name) LIKE '%RUBBERIZED COATING%'
       OR UPPER(name) LIKE '%ROCK GUARD%'
       OR UPPER(name) LIKE '%STONE GUARD%'
       OR UPPER(name) LIKE '%RAIN GUTTER%'
       OR UPPER(name) LIKE '%GUTTER SPOUT%'
       OR UPPER(name) LIKE '%DURAPATCH%'
       OR UPPER(name) LIKE '%UNDERBELLY%'
       OR UPPER(name) LIKE '%BELLY BOTTOM%'
       OR UPPER(name) LIKE '%JWRAP SKIRT%'
       OR UPPER(name) LIKE '%GRAY BUTLY%'
       OR UPPER(name) LIKE '%HTTMT%'
       OR UPPER(name) LIKE '%IMPACT-RES%'
  );

-- → DOORS/WINDOWS/AWNINGS
UPDATE inventory SET category = 'DOORS/WINDOWS/AWNINGS', updated_at = NOW()
WHERE category = 'MISC/SHOP SUPPLIES'
  AND (
       UPPER(name) LIKE '%AWNING FABRIC%'
       OR UPPER(name) LIKE '%CAREFREE AWNING%'
       OR UPPER(name) LIKE '%SOLERA%'
       OR UPPER(name) LIKE '%SLIDE TOPPER%'
       OR UPPER(name) LIKE '%SLIDE ROOM%'
       OR UPPER(name) LIKE '%SLIDEOUT%'
       OR UPPER(name) LIKE '%SCHWINTEK%'
       OR UPPER(name) LIKE '%LIPPERT SLIDE%'
       OR UPPER(name) LIKE '%SLIDE MOTOR%'
       OR UPPER(name) LIKE '%SLIDE DRIVE%'
       OR UPPER(name) LIKE '%GEAR MOTOR SLIDE%'
       OR UPPER(name) LIKE '%ACCUE SLIDE%'
       OR UPPER(name) LIKE '%H TRACK%'
       OR UPPER(name) LIKE '%H-COLUMN%'
       OR UPPER(name) LIKE '%SLIDE FABRIC%'
       OR UPPER(name) LIKE '%TOPPER FABRIC%'
       OR UPPER(name) LIKE '%TOPPER SPRING%'
       OR UPPER(name) LIKE '%WINDOW KNOB%'
       OR UPPER(name) LIKE '%THUMB COMPARTMENT%'
       OR UPPER(name) LIKE '%KEYED COMPARTMENT%'
       OR UPPER(name) LIKE '%DOUBLE ROLLER CATCH%'
       OR UPPER(name) LIKE '%BULL DOG CATCH%'
       OR UPPER(name) LIKE '%DRAWER SLIDE SOCKET%'
       OR UPPER(name) LIKE '%GRABBER CATCHES%'
       OR UPPER(name) LIKE '%ANGLED T-STYLE%'
       OR UPPER(name) LIKE '%DRAWER SLIDE%'
       OR UPPER(name) LIKE '%CLAW BAR%'
       OR UPPER(name) LIKE '%SMOKED VENT LID%'
       OR UPPER(name) LIKE '%WHITE VENT LID%'
       OR UPPER(name) LIKE '%BVD0449%'
       OR UPPER(name) LIKE '%SKYLIGHT INNER%'
       OR UPPER(name) LIKE '%RADIUS CORNER 14X14%'
       OR UPPER(name) LIKE '%STEP LIPPERT%'
       OR UPPER(name) LIKE '%TORKLIFT%'
       OR UPPER(name) LIKE '%KWIKEE STEP%'
       OR UPPER(name) LIKE '%AIRSTREAM DOUBLE STEP%'
       OR UPPER(name) LIKE '%BLACK LEFT MOUNT STEP%'
       OR UPPER(name) LIKE '%WINDSHIELD TRIANGLE%'
       OR UPPER(name) LIKE '%PRIVACY GLASS%'
       OR UPPER(name) LIKE '%MEDICINE CABINET%'
       OR UPPER(name) LIKE '%TOWEL RING%'
       OR UPPER(name) LIKE '%INNER ARMS%'
       OR UPPER(name) LIKE '%OUTER ARMS%'
       OR UPPER(name) LIKE '%GEARPACKS%'
       OR UPPER(name) LIKE '%SATIN CASE SLATS%'
       OR UPPER(name) LIKE '%SPRING EYE BUSHING%'
       OR UPPER(name) LIKE '%RAFTER COLLAR%'
       OR UPPER(name) LIKE '%RETAINER SPLINE%'
       OR UPPER(name) LIKE '%ASCENT CVR%'
       OR UPPER(name) LIKE '%76_ ASCENT%'
       OR UPPER(name) LIKE '%RECPRO SKLIGHT%'
       OR UPPER(name) LIKE '%SCT RV SKILIGHT%'
       OR UPPER(name) LIKE '%SHADE/SCREEN%'
       OR UPPER(name) LIKE '%LARGE HATCH%'
       OR UPPER(name) LIKE '%KTN 8%'
       OR UPPER(name) LIKE '%SHW 4%'
  );

-- → TOWING/CHASSIS
UPDATE inventory SET category = 'TOWING/CHASSIS', updated_at = NOW()
WHERE category = 'MISC/SHOP SUPPLIES'
  AND (
       UPPER(name) LIKE '%AXLE%'
       OR UPPER(name) LIKE '%BRAKE ASSEMBL%'
       OR UPPER(name) LIKE '%BRAKE MAGNET%'
       OR UPPER(name) LIKE '%BRAKE PLATE%'
       OR UPPER(name) LIKE '%HUB%'
       OR UPPER(name) LIKE '%DRUM%'
       OR UPPER(name) LIKE '%BEARING%'
       OR UPPER(name) LIKE '%WHEEL SEAL%'
       OR UPPER(name) LIKE '%HITCH%'
       OR UPPER(name) LIKE '%COUPLER%'
       OR UPPER(name) LIKE '%TRAILER JACK%'
       OR UPPER(name) LIKE '%JACK BASE%'
       OR UPPER(name) LIKE '%JACK CRANK%'
       OR UPPER(name) LIKE '%DEXTER%'
       OR UPPER(name) LIKE '%ELECTRIC BRAKE%'
       OR UPPER(name) LIKE '%WEAR TABS%'
       OR UPPER(name) LIKE '%FIFTH WHEEL%'
       OR UPPER(name) LIKE '%LUBE PLATE%'
       OR UPPER(name) LIKE '%TIMKIN%'
       OR UPPER(name) LIKE '%TIMKEN%'
       OR UPPER(name) LIKE '%WHEEL WELL%'
       OR UPPER(name) LIKE '%BRAKLEEN%'
       OR UPPER(name) LIKE '%BRAKE CLEAN%'
       OR UPPER(name) LIKE '%DENCO BRAKE%'
       OR UPPER(name) LIKE '%HEATER HOSE%'
       OR UPPER(name) LIKE '%EXHAUST HANGER%'
       OR UPPER(name) LIKE '%SHOCK ABSORB%'
       OR UPPER(name) LIKE '%EQUALIZER%'
       OR UPPER(name) LIKE '%SWAY CONTROL%'
       OR UPPER(name) LIKE '%WEIGHT DIST%'
       OR UPPER(name) LIKE '%SPRING LEAF%'
       OR UPPER(name) LIKE '%LEAF SPRING%'
       OR UPPER(name) LIKE '%SAFETY CHAIN%'
       OR UPPER(name) LIKE '%SAFTY CHAIN%'
       OR UPPER(name) LIKE '%ALUMINUM WHEEL%'
       OR UPPER(name) LIKE '% RIM %'
       OR UPPER(name) LIKE '%FENDER SKIRT%'
       OR UPPER(name) LIKE '%PICK-UP TRUCK COVER%'
       OR UPPER(name) LIKE '%UNIVERSAL JOINT%'
       OR UPPER(name) LIKE '%EQ SYSTEMS CROSS BAR%'
       OR UPPER(name) LIKE '%MORRYDE%'
       OR UPPER(name) LIKE '%TANDEM WET KIT%'
       OR UPPER(name) LIKE '%TONGUE WEIGHT%'
       OR UPPER(name) LIKE '%TRAILER TONGUE BATTERY BOX%'
  );

-- → HARDWARE
UPDATE inventory SET category = 'HARDWARE', updated_at = NOW()
WHERE category = 'MISC/SHOP SUPPLIES'
  AND (
       UPPER(name) LIKE '%SCREW%'
       OR UPPER(name) LIKE '%BOLT %'
       OR UPPER(name) LIKE '%NUT %'
       OR UPPER(name) LIKE '%WASHER%'
       OR UPPER(name) LIKE '%RIVET%'
       OR UPPER(name) LIKE '%L BRACKET%'
       OR UPPER(name) LIKE '%CORNER BRACE%'
       OR UPPER(name) LIKE '%SS CLAMP%'
       OR UPPER(name) LIKE '%STIFFNER%'
       OR UPPER(name) LIKE '%MARINE COT%'
       OR UPPER(name) LIKE '%MOLDING%'
       OR UPPER(name) LIKE '%BELTLINE%'
       OR UPPER(name) LIKE '%RUB RAIL%'
       OR UPPER(name) LIKE '%RUBRAIL%'
       OR UPPER(name) LIKE '%CHROME INSERT%'
       OR UPPER(name) LIKE '%ANGLE IRON%'
       OR UPPER(name) LIKE '%LAUAN%'
       OR UPPER(name) LIKE '%SANDE PLYWOOD%'
       OR UPPER(name) LIKE '%CARPET TILE%'
       OR UPPER(name) LIKE '%VELCRO%'
       OR UPPER(name) LIKE '%WIDE FLEX KEY%'
       OR UPPER(name) LIKE '%FLEX KEY%'
       OR UPPER(name) LIKE '%CROWN STAPLE%'
       OR UPPER(name) LIKE '%REFLEXIVE INSULATION%'
       OR UPPER(name) LIKE '%ECOBATT INSULATION%'
       OR UPPER(name) LIKE '%FOAM INSULATION%'
       OR UPPER(name) LIKE '%CLOROPLAST%'
       OR UPPER(name) LIKE '%PLASTIC TRAY%'
       OR UPPER(name) LIKE '%TRAY LINER%'
       OR UPPER(name) LIKE '%SPRING PIN%'
       OR UPPER(name) LIKE '%SPLIT SPRING%'
       OR UPPER(name) LIKE '%STUDS %'
       OR UPPER(name) LIKE '%PANEL 22.50%'
       OR UPPER(name) LIKE '%PRE LAMINATE%'
       OR UPPER(name) LIKE '%BLACK FOOT INSERT%'
       OR UPPER(name) LIKE '%LIP INSERT%'
       OR UPPER(name) LIKE '%LEG INSERT%'
       OR UPPER(name) LIKE '%VINYL CAP BASE%'
       OR UPPER(name) LIKE '%VINYL INSERT%'
       OR UPPER(name) LIKE '%D SEAL %'
       OR UPPER(name) LIKE '%3/8-16 X 3.50%'
       OR UPPER(name) LIKE '%METAL MAGERY%'
       OR UPPER(name) LIKE '%NARROW BODY BOW%'
       OR UPPER(name) LIKE '%SUPPORT BRACE LOWER%'
       OR UPPER(name) LIKE '%FLAT METAL RADIUS%'
       OR UPPER(name) LIKE '%ALTERNATIVE PA%'
       OR UPPER(name) LIKE '%EPOXY BLACK%'
       OR UPPER(name) LIKE '%RESEN APPOXY%'
       OR UPPER(name) LIKE '%VINAL ROUND BUMPER%'
       OR UPPER(name) LIKE '%4" C CLAMP%'
       OR UPPER(name) LIKE '%1 INCH BLACK VINYL%'
       OR UPPER(name) LIKE '%ANG 1.5 X%'
       OR UPPER(name) LIKE '%TITAN SLEEVE%'
       OR UPPER(name) LIKE '%5/16 GROMET%'
       OR UPPER(name) LIKE '%CLAMPS %'
       OR UPPER(name) LIKE '%SS TEKS%'
       OR UPPER(name) LIKE '%3/4 SPLIT%'
       OR UPPER(name) LIKE '%INSULATED 1" CLAMP%'
  );

-- STEP 3: Move Airstream-specific parts into AIRSTREAM category
-- Pulls from HARDWARE, MISC/SHOP SUPPLIES, and any other category

UPDATE inventory SET category = 'AIRSTREAM', updated_at = NOW()
WHERE (
       UPPER(name) LIKE '%AIRSTREAM%'
       OR UPPER(name) LIKE '%AIRSTR%'
       OR UPPER(name) LIKE '%ARCTIC CENTER RADIUS%'
       OR UPPER(name) LIKE '%EXTRUSION BELTLINE%'
       OR UPPER(name) LIKE '%EXTRUSION RUBRAIL%'
       OR UPPER(name) LIKE '%Z-EXTRUSION%'
       OR UPPER(name) LIKE '%Z EXTRUSION%'
       OR UPPER(name) LIKE '%FRONT METAL BOTTOM SHEET%'
       OR UPPER(name) LIKE '%FRONT METAL 2ND%'
       OR UPPER(name) LIKE '%METAL - SKIRT%'
       OR UPPER(name) LIKE '%METAL SKIRT%'
       OR UPPER(name) LIKE '%#4 METAL POLAR%'
       OR UPPER(name) LIKE '%#3 METAL PWTR%'
       OR UPPER(name) LIKE '%BROWN METAL 91%'
       OR UPPER(name) LIKE '%RUB RAIL CHROME INSERT%'
       OR UPPER(name) LIKE '%RUBRAIL%'
       OR UPPER(name) LIKE '%REAR CS SKIRTING%'
       OR UPPER(name) LIKE '%REAR CENTER UNDERBELLY%'
       OR UPPER(name) LIKE '%BANANA WRAP%'
       OR UPPER(name) LIKE '%CENTER PC STONE GUARD%'
       OR UPPER(name) LIKE '%NO-BO%'
       OR UPPER(name) LIKE '%NOBO%'
       OR UPPER(name) LIKE '%NOBOFRONT%'
       OR UPPER(name) LIKE '%FRONT WALL WHITE%'
       OR UPPER(name) LIKE '%ALUMINUM SHEET%'
       OR UPPER(name) LIKE '%ALUMINUM LOWER SHEET%'
       OR UPPER(name) LIKE '%ALUMINUM SIDE SHEET%'
       OR UPPER(name) LIKE '%ALUMINUM SHEET .040%'
       OR UPPER(name) LIKE '%UNDERBELLY WRAP%'
       OR UPPER(name) LIKE '%UNDERBELLY SKIN%'
       OR UPPER(name) LIKE '%UNDERBELLY FLEX%'
       OR UPPER(name) LIKE '%BELLY BOTTOM REPAIR%'
       OR UPPER(name) LIKE '%JWRAP SKIRT%'
       OR UPPER(name) LIKE '%AIRSTREAM STABILIZER%'
       OR UPPER(name) LIKE '%AIRSTREAM GABRIEL%'
       OR UPPER(name) LIKE '%AIRSTREAM MEDICINE%'
       OR UPPER(name) LIKE '%AIRSTREAM DOUBLE STEP%'
       OR UPPER(name) LIKE '%AIRSTREAM FRONT SEPARATION%'
       OR UPPER(name) LIKE '%AFSK%'
       OR UPPER(name) LIKE '%SERENITY 3" BADGE%'
       OR UPPER(name) LIKE '%SERENITY BADGE%'
       OR UPPER(name) LIKE '%HEAD CASTING%'
       OR UPPER(name) LIKE '%JAYCO DECAL%'
       OR UPPER(name) LIKE '%GRAPHIC, DC%'
       OR UPPER(name) LIKE '%GRAPHIC, DE%'
       OR UPPER(name) LIKE '%JY16JF%'
       OR UPPER(name) LIKE '%JAYFLIGHT%'
       OR UPPER(name) LIKE '%NO-BO LARGE LEGEND%'
       OR UPPER(name) LIKE '%NOBO ODS FRONT%'
       OR UPPER(name) LIKE '%NO-BO DS FRONT%'
       OR UPPER(name) LIKE '%FASCIA #M41115%'
       OR UPPER(name) LIKE '%NARROW BODY BOW%'
       OR UPPER(name) LIKE '%SUPPORT BRACE LOWER END%'
       OR UPPER(name) LIKE '%UPPER ROADSIDE SHEET%'
       OR UPPER(name) LIKE '%SEGMENT CENTER%'
       OR UPPER(name) LIKE '%SEGMENT #%'
);

COMMIT;

-- Verify final category breakdown:
-- SELECT category, COUNT(*) FROM inventory GROUP BY category ORDER BY category;